# Posts

## Получить список постов по фильтру 648993f802b256e0ca1cb09b

GET http://localhost:3000/posts?userId=111111111111111111111111&type=text&tags=tag1 tag2 tag3&sort=likeCount HTTP/1.1

###

## Получить список постов по фильтру

GET http://localhost:3000/posts?userId=111111111111111111111111&type=text&tags=tag1 tag2 tag3 HTTP/1.1

###
