# Users

# Login user by email and password
POST http://localhost:4444/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "password": "111111"
}

###{
###  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZGM1NTg3YzYyOTkwOGNhMTQwYTE2NiIsImVtYWlsIjoidG9yYW5zQG92ZXJsb29rLm5ldCIsIm5hbWUiOiJKYWNrIiwiaWF0IjoxNjkyOTQ0NDM4LCJleHAiOjE2OTU1MzY0Mzh9.lgMPgUsqP1lle0TVciBcbZHdAH4kNHYDJZI-JFlq4MY",
###  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZGM1NTg3YzYyOTkwOGNhMTQwYTE2NiIsImVtYWlsIjoidG9yYW5zQG92ZXJsb29rLm5ldCIsIm5hbWUiOiJKYWNrIiwidG9rZW5JZCI6IjkyNTBjNGJlLTdiMDAtNGNhNy1hZDJiLWIxNDA3YWFhZDIwMiIsImlhdCI6MTY5Mjk0NDQzOCwiZXhwIjoxNjk1NTM2NDM4fQ.Jmp2HmP-Pf3tpAgXgSBZo7BYg2C_CfJbRP-4CPedvqU"
###}

###

## Авторизовать пользователя

POST http://localhost:4444/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "snow@pisem.local",
  "password": "111111"
}

###{
###  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZGM5OTZlMmM3NDA4MmZiYzdiNzBjZCIsImVtYWlsIjoic25vd0BwaXNlbS5sb2NhbCIsIm5hbWUiOiJCb2IiLCJpYXQiOjE2OTMzMTIwOTcsImV4cCI6MTY5NTkwNDA5N30.l0U5PE9RR4h1D_z-IDn96v3X-ADxpms_8gkRqJhg1lo",
###  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZGM5OTZlMmM3NDA4MmZiYzdiNzBjZCIsImVtYWlsIjoic25vd0BwaXNlbS5sb2NhbCIsIm5hbWUiOiJCb2IiLCJ0b2tlbklkIjoiNjBlOWNmNzctZWUyNC00Mzc4LWE0YmItZjE5OTk2MTE4MDdkIiwiaWF0IjoxNjkzMzEyMDk3LCJleHAiOjE2OTU5MDQwOTd9.2h73b9gq0A0E_W0x0uHDkO4BVXcXaTiyCumqi3j2R9Q"
###}

###
