# Users

## Создать нового пользователя

POST http://localhost:4444/users/register HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar-angelina.jpg"
Content-Type: image/jpeg

< /Users/User/Pictures/avatar-angelina.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="user"
Content-Type: text/plain

{
  "email": "tornsant@overbook.com",
  "name": "Jack",
  "password": "shining"
}

###

## Создать нового пользователя с плохим аватаром

POST http://localhost:4444/users/register HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar-angelina.jpg"
Content-Type: image/jpeg

< /Users/User/Documents/Палитра.txt

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="user"
Content-Type: text/plain

{
  "email": "tornsant@overbook.com",
  "name": "Jack",
  "password": "shining"
}

###

##Get user by id

GET http://localhost:4444/users/64dc5587c629908ca140a166 HTTP/1.1

###


# Get new JWT pair
POST http://localhost:4444/users/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZGM1NTg3YzYyOTkwOGNhMTQwYTE2NiIsImVtYWlsIjoidG9yYW5zQG92ZXJsb29rLm5ldCIsIm5hbWUiOiJKYWNrIiwidG9rZW5JZCI6IjkyNTBjNGJlLTdiMDAtNGNhNy1hZDJiLWIxNDA3YWFhZDIwMiIsImlhdCI6MTY5Mjk0NDQzOCwiZXhwIjoxNjk1NTM2NDM4fQ.Jmp2HmP-Pf3tpAgXgSBZo7BYg2C_CfJbRP-4CPedvqU

###


# Change password
PATCH http://localhost:4444/users/password HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZGM1NTg3YzYyOTkwOGNhMTQwYTE2NiIsImVtYWlsIjoidG9yYW5zQG92ZXJsb29rLm5ldCIsIm5hbWUiOiJKYWNrIiwiaWF0IjoxNjkyOTQ0NDM4LCJleHAiOjE2OTU1MzY0Mzh9.lgMPgUsqP1lle0TVciBcbZHdAH4kNHYDJZI-JFlq4MY
Content-Type: application/json

{
  "oldPassword": "222222",
  "newPassword": "111111"
}

###

## Создать нового пользователя

PATCH http://localhost:4444/users/register HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar-angelina.jpg"
Content-Type: image/jpeg

< /Users/User/Pictures/avatar-angelina.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="user"
Content-Type: text/plain

{
  "email": "tornsant@overbook.com",
  "name": "Jack",
  "password": "shining"
}

###

## Создать нового пользователя

PATCH http://localhost:4444/users/update HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZGM1NTg3YzYyOTkwOGNhMTQwYTE2NiIsImVtYWlsIjoidG9yYW5zQG92ZXJsb29rLm5ldCIsIm5hbWUiOiJKYWNrIiwiaWF0IjoxNjkyOTQ0NDM4LCJleHAiOjE2OTU1MzY0Mzh9.lgMPgUsqP1lle0TVciBcbZHdAH4kNHYDJZI-JFlq4MY

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar-angelina.jpg"
Content-Type: image/jpeg

< /Users/User/Pictures/avatar-angelina.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="user"
Content-Type: text/plain

{
  "name": "Jack"
}

###
