# Followers

## Подписаться на пользователя

POST http://localhost:4444/followers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZGM1NTg3YzYyOTkwOGNhMTQwYTE2NiIsImVtYWlsIjoidG9yYW5zQG92ZXJsb29rLm5ldCIsIm5hbWUiOiJKYWNrIiwiaWF0IjoxNjkyOTQ0NDM4LCJleHAiOjE2OTU1MzY0Mzh9.lgMPgUsqP1lle0TVciBcbZHdAH4kNHYDJZI-JFlq4MY
Content-Type: application/json

{
  "followed": "64dc996e2c74082fbc7b70cd"
}

###

## Подписаться на себя

POST http://localhost:4444/followers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZGM1NTg3YzYyOTkwOGNhMTQwYTE2NiIsImVtYWlsIjoidG9yYW5zQG92ZXJsb29rLm5ldCIsIm5hbWUiOiJKYWNrIiwiaWF0IjoxNjkyOTQ0NDM4LCJleHAiOjE2OTU1MzY0Mzh9.lgMPgUsqP1lle0TVciBcbZHdAH4kNHYDJZI-JFlq4MY
Content-Type: application/json

{
  "followed": "64dc5587c629908ca140a166"
}

###

DELETE http://localhost:4444/followers/64dc996e2c74082fbc7b70cd HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZGM1NTg3YzYyOTkwOGNhMTQwYTE2NiIsImVtYWlsIjoidG9yYW5zQG92ZXJsb29rLm5ldCIsIm5hbWUiOiJKYWNrIiwiaWF0IjoxNjkyOTQ0NDM4LCJleHAiOjE2OTU1MzY0Mzh9.lgMPgUsqP1lle0TVciBcbZHdAH4kNHYDJZI-JFlq4MY

###

## Подписаться на пользователя

POST http://localhost:4444/followers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZGM5OTZlMmM3NDA4MmZiYzdiNzBjZCIsImVtYWlsIjoic25vd0BwaXNlbS5sb2NhbCIsIm5hbWUiOiJCb2IiLCJpYXQiOjE2OTMzMTIwOTcsImV4cCI6MTY5NTkwNDA5N30.l0U5PE9RR4h1D_z-IDn96v3X-ADxpms_8gkRqJhg1lo
Content-Type: application/json

{
  "followed": "64dc5587c629908ca140a166"
}

###

DELETE http://localhost:4444/followers/64dc5587c629908ca140a166 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZGM5OTZlMmM3NDA4MmZiYzdiNzBjZCIsImVtYWlsIjoic25vd0BwaXNlbS5sb2NhbCIsIm5hbWUiOiJCb2IiLCJpYXQiOjE2OTMzMTIwOTcsImV4cCI6MTY5NTkwNDA5N30.l0U5PE9RR4h1D_z-IDn96v3X-ADxpms_8gkRqJhg1lo

###

## Подписаться на пользователя

POST http://localhost:4444/followers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZGM5OTZlMmM3NDA4MmZiYzdiNzBjZCIsImVtYWlsIjoic25vd0BwaXNlbS5sb2NhbCIsIm5hbWUiOiJCb2IiLCJpYXQiOjE2OTMzMTIwOTcsImV4cCI6MTY5NTkwNDA5N30.l0U5PE9RR4h1D_z-IDn96v3X-ADxpms_8gkRqJhg1lo
Content-Type: application/json

{
  "followed": "64e0ec87d781487f0d6795d8"
}

###

DELETE http://localhost:4444/followers/64e0ec87d781487f0d6795d8 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZGM5OTZlMmM3NDA4MmZiYzdiNzBjZCIsImVtYWlsIjoic25vd0BwaXNlbS5sb2NhbCIsIm5hbWUiOiJCb2IiLCJpYXQiOjE2OTMzMTIwOTcsImV4cCI6MTY5NTkwNDA5N30.l0U5PE9RR4h1D_z-IDn96v3X-ADxpms_8gkRqJhg1lo

###
