# Posts

## Создать новый пост типа текст user: "torans@overlook.net"

POST http://localhost:4444/posts/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZGM1NTg3YzYyOTkwOGNhMTQwYTE2NiIsImVtYWlsIjoidG9yYW5zQG92ZXJsb29rLm5ldCIsIm5hbWUiOiJKYWNrIiwiaWF0IjoxNjkyOTQ0NDM4LCJleHAiOjE2OTU1MzY0Mzh9.lgMPgUsqP1lle0TVciBcbZHdAH4kNHYDJZI-JFlq4MY
Content-Type: application/json

{
  "type": "text",
  "content": {
    "title": "еду на коняге torans@overlook.net",
    "announcement": "песнь степного коневодителя, и этот пост тоже должен torans@overlook.net",
    "text": "Степь да степь кругом, путь далёк лежит, в той степи глухой замерзал ямщик. И текст этого поста тоже должен."
  },
  "tags": [
    "зима",
    "степь",
    "холод",
    "конь"
  ]
}

###
